# Configuration file for concept bottleneck model experiments

experiment_name: "bird_classification"  # Name of the experiment for logging purposes

#Meta
dataset_name: "CUB"  # Name of the dataset (currently supports "CUB" for Caltech-UCSD Birds)
seed: 1 # Random seed
mode: Joint #"Standard", "Independent", "Joint", "Sequential","End"  # List of training modes to iterate over
device: "auto"  # Device to use for training ("auto" for automatic detection, "cuda" for GPU, "cpu" for CPU)


#dataset
#image_dir: data/CUB_200_2011/images # test image folder to run inference on'
#data_dir: data/CUB_processed/filtered  # Path to the dataset directory with anotoated pickle files note that the data directory should contain the following files: 'train.pkl', 'val.pkl', 'test.pkl' not the images
#resampling: False  # Whether to use resampling

logger:
  use_wandb: True  # Enable/disable W&B logging
  project_name: ${experiment_name}  # Use experiment name as project name
  run_name: null  # If null, will auto-generate based on mode and timestamp
  group: ${mode}  # Group runs by training mode
  tags: 
    - ${dataset_name}
    - ${mode}


CUB_dataloader: # Paremeter for the CUB dataloader
  CUB_dir: data/CUB_200_2011 # Path to the CUB dataset directory
  split_file: data//train_test_val.pkl # Path to the split file

  #Concept (attributes) settings
  return_visibility: False # Whether to return visibility labels can not be used with majority voting if return_concepts is True the dataloader will return a tuple of (concept_labels, visibility_labels)

  use_majority_voting: False  # Whether to use majority voting for concepts labels
  min_class_count: 10 # apply the filer that removes concepts present in less than min_class_count classes only relevant after majority voting if false use all 320 concepts
  hard_concept: False # Only used when making new dataset by using XtoC model make new C binary, else it is sigmoid. 



#training
batch_size: 32
epochs: 500 #2000  # Number of training epochs
lr: 0.001  # Initial learning rate for optimization
optimizer: 'Adam' # Optimizer to use for training (e.g., "Adam", "SGD", "RMSprop")
momentum: 0.9  # Momentum factor for SGD optimizer
weight_decay: 0.000004 #0.000004  # Weight decay (L2 penalty) for optimization
lambda1: 0.0001  # Weighting factor for concept loss in joint training
scheduler_step: 20  # Number of steps before decaying current learning rate by half
lr_decay_size: 0.94 #0.94  # Learning rate decay factor
weighted_loss: False # 'Whether to use weighted the positive loss for concept prediction
#normalize_loss: False # Whether to normalize loss by taking attr_loss_weight into account
transform_method: "original" # Transformation method for the concept bottleneck model ("original","resize","center")



#models
concept_model: "inception"  # Type of model for concept prediction only "inception" is supported
pretrained: True  # Whether to use pretrained weights for the concept model
ckpt: False  #  if true combine train and val data to train the model
freeze: false  # Whether to freeze the bottom part of the inception network
use_aux: True # Whether to use auxiliary outputs in the inception network

#output directorys
log_dir: None  # Directory to save logs and model checkpoints


#Concept model always use sigmoid activation
#use_relu: False #use relu activation in the end of the concpet classifyer.
#use_sigmoid: True #use sigmoid relu activation in the end of the concpet classifyer.