
experiment_name: "bird_classification"  # Name of the experiment for logging purposes
dataset_name: "CUB"  # Name of the dataset (currently supports "CUB" for Caltech-UCSD Birds)

mode: "Sequential" #"Standard", "Independent", "Joint", "Sequential"  # List of training modes to iterate over



joint_path: "models/Original_joint/best_model_1.pth"  # Path to the joint model

XtoC_path: "models/Sequential_CKTP_NoPretraining/best_XtoC_model.pth"  # Path to first part of sequential and independent model
CtoY_path: "models/Sequential_CKTP_NoPretraining/best_CtoY_model.pth"  # Path to second part of sequential and independent model

XtoY_path: "models/Original_standard/best_model_1.pth"  # Path to the model directory

output_dir: "models/Sequential_CKTP_NoPretraining"  # Directory to save evaluation results if blank will use the model directory

device: "auto"  # Device to use for training ("auto" for automatic detection, "cuda" for GPU, "cpu" for CPU)

transform_method: "center" # Transformation method for the concept bottleneck model ("original","resized","center")


logger:
  use_wandb: True  # Enable/disable W&B logging
  project_name: ${experiment_name}  # Use experiment name as project name
  run_name: null  # If null, will auto-generate based on mode and timestamp
  group: "Evaluation_${mode}"  # Group runs by training mode
  tags: 
    - ${dataset_name}
    - ${mode}

split: test # Selcet val or test
original_model: False

sailency: False # Calulate sailency score.
sailency_methode: "vanilla"  

CUB_dataloader:
  CUB_dir: data/CUB_200_2011

CUB_NonMajority_dataloader: # Paremeter for the CUB dataloader
  CUB_dir: data/CUB_200_2011 # Path to the CUB dataset directory
  split_file: data/train_test_val.pkl # Path to the split file

  #Concept (attributes) settings
  return_concepts: False # Whether to return concept labels
  return_visibility: False # Whether to return visibility labels can not be used with majority voting if return_concepts is True the dataloader will return a tuple of (concept_labels, visibility_labels)

  use_majority_voting: False # Whether to use majority voting for concepts labels
  min_class_count: 0 # apply the filer that removes concepts present in less than min_class_count classes only relevant after majority voting if false use all 320 concepts

CUB_majority_dataloader: # Load a a dataloader with majority voting if this dataset has fewer classes only those classes will be used for both evaluations 
  CUB_dir: data/CUB_200_2011 # Path to the CUB dataset directory
  split_file: data/train_test_val.pkl # Path to the split file

  #Concept (attributes) settings
  return_concepts: False # Whether to return concept labels
  return_visibility: False # Whether to return visibility labels can not be used with majority voting if return_concepts is True the dataloader will return a tuple of (concept_labels, visibility_labels)

  use_majority_voting: True # Whether to use majority voting for concepts labels
  min_class_count: 10 # apply the filer that removes concepts present in less than min_class_count classes only relevant after majority voting if false use all 320 concepts


